### ISSUE TITLE
"There is no function named 'aWarpSharp2"

### ISSUE THREAD

**Issue by ENunn** [jpsdr/aWarpSharpMT#2]
I've put the DLL in my plugins64+ folder but its not wanting to work. It keeps giving me this:
![image](https://user-images.githubusercontent.com/19480682/63641421-997aa080-c673-11e9-83c6-8da6024cf162.png)

Whenever I try to use LoadPlugin it gives me this:
![image](https://user-images.githubusercontent.com/19480682/63641428-c0d16d80-c673-11e9-926b-bfcedf910cbf.png)

How do I fix this?

**Comment by jpsdr** [comment]
Are the Visual Studio and/or Intel redistribuable (according the version you used) installed and up to date ? Check the ReadMe.txt in the root of x64 directory.

**Comment by jpsdr** [comment]
No feedback after several months, issue closed.
