### ISSUE TITLE
Threshold not 0-255 but 0-1

### ISSUE THREAD

**Issue by Selur** [jpsdr/aWarpSharpMT#4]
with build 28/04/2020.
using aWarpSharp(thresh=2), I get aWarpSharp 'thresh' must be 0..255
using 0.01-1 works without a problem

**Comment by Selur** [comment]
small correction works for [0-1[ so not for 1.

**Comment by jpsdr** [comment]
At the end of the _aWarpSharp.txt_ :
Original aWarpSharp compatibility:
  Mapping from original aWarpSharp parameters:
    thresh = thresh*256
    blur   = blurlevel
    depth  = depth*blurlevel/2
    chroma = 0->2, 1->4, 2->3

  This version is able to do the conversion automatically when called as aWarpSharp,
  but errors in case of out of bounds values will be displayed in new terms.

**Comment by Selur** [comment]
Ah okay, I assumed aWarpSharp now also uses 0-255.
Thanks for clearing that up.
